{application,todo,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"todo"},
              {modules,['Elixir.Todo.Cache','Elixir.Todo.Database',
                        'Elixir.Todo.DatabaseWorker','Elixir.Todo.List',
                        'Elixir.Todo.Server','Elixir.Todo.Supervisor']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
